services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    rootDir: backend   # 👈 this tells Render to deploy from subfolder
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
