"""Increased embeddings dimensions

Revision ID: 3f346cff0c2d
Revises: 31e7a9e8fdbc
Create Date: 2025-09-13 03:02:28.729644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3f346cff0c2d'
down_revision: Union[str, Sequence[str], None] = '31e7a9e8fdbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'embeddings',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'embeddings',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###
