"""describe your changes

Revision ID: 44ce61e5e31f
Revises: 59c9976128ac
Create Date: 2025-09-14 01:01:44.649118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ce61e5e31f'
down_revision: Union[str, Sequence[str], None] = '59c9976128ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('indexed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'indexed')
    # ### end Alembic commands ###
