"""made indexed column nullable

Revision ID: 4622b2c02162
Revises: 44ce61e5e31f
Create Date: 2025-09-14 01:03:43.395424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4622b2c02162'
down_revision: Union[str, Sequence[str], None] = '44ce61e5e31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('indexed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'indexed')
    # ### end Alembic commands ###
