"""Added city and region

Revision ID: 59c9976128ac
Revises: 31e7a9e8fdbc
Create Date: 2025-09-13 13:26:50.008018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '59c9976128ac'
down_revision: Union[str, Sequence[str], None] = '31e7a9e8fdbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('events', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'region')
    op.drop_column('events', 'city')
    # ### end Alembic commands ###
